format = """
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$time\
$battery\
$docker_context\
$line_break\
$python\
$nodejs\
$rust\
$golang\
$character"""


[directory]
style = "bold #F28B09"
truncation_length = 3
truncate_to_repo = true


[git_branch]
format = "[$branch]($style) "
style = "#7A11FF"


[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
min_time = 500
format = "[$duration]($style) "
style = "#FAFE71"

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[[battery.display]] 
threshold = 10
style = 'bold red'
discharging_symbol = 'ğŸš¨'

[[battery.display]] 
threshold = 30
style = 'bold yellow'
discharging_symbol = 'ğŸ’¦ '

[docker_context]
symbol = "ğŸ‹"
format = "via [$symbol$context]($style) "
style = "blue bold"
disabled = false 

[python]
format = "[$virtualenv]($style) "
symbol = "ğŸ"
style = "bright-black"

[nodejs]
format = "[$symbol$version]($style) "
symbol = "ğŸ“¦"
style = "bright-black"

[rust]
format = "[$version]($style) "
symbol = "ğŸ¦€"
style = "bright-black"

[golang]
format = "[$version]($style) "
symbol = "ğŸ¹"
style = "bright-black"

[character]
success_symbol = "[â¯](bold #64FF1A)"
error_symbol = "[!](bold #FF0000)"
vimcmd_symbol = "[â®](bold #68FBFF)"
